/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author l
 */
public class MenuAkademik extends javax.swing.JFrame {

    /**
     * Creates new form MenuAkademik
     */
    public MenuAkademik() {
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuMahasiswa = new javax.swing.JMenuItem();
        mnuMatakuliah = new javax.swing.JMenuItem();
        mnuPeriode = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mnuKRSS = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        mnuCetakDataMahasiswa = new javax.swing.JMenuItem();
        mnuCetakDataMatakuliah = new javax.swing.JMenuItem();
        mnuCetakKRSS = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        mnuMahasiswa.setText("Mahasiswa");
        mnuMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMahasiswaActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMahasiswa);

        mnuMatakuliah.setText("Matakuliah");
        mnuMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMatakuliahActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMatakuliah);

        mnuPeriode.setText("Periode");
        mnuPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPeriodeActionPerformed(evt);
            }
        });
        mnuFile.add(mnuPeriode);
        mnuFile.add(jSeparator3);

        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        jMenuBar1.add(mnuFile);

        mnuTransaksi.setText("Transaksi");
        mnuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTransaksiActionPerformed(evt);
            }
        });

        mnuKRSS.setText("KRSS");
        mnuKRSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKRSSActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuKRSS);

        jMenuBar1.add(mnuTransaksi);

        mnuLaporan.setText("Laporan");

        mnuCetakDataMahasiswa.setText("Cetak Data Mahasiswa");
        mnuCetakDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCetakDataMahasiswaActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuCetakDataMahasiswa);

        mnuCetakDataMatakuliah.setText("Cetak Data Matakuliah");
        mnuLaporan.add(mnuCetakDataMatakuliah);

        mnuCetakKRSS.setText("Cetak  KRSS");
        mnuLaporan.add(mnuCetakKRSS);

        jMenuBar1.add(mnuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCetakDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCetakDataMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCetakDataMahasiswaActionPerformed

    private void mnuKRSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKRSSActionPerformed
        View.FrmKRSS objKrs= new View.FrmKRSS();
        objKrs.setLocationRelativeTo(this);
        objKrs.setVisible(true);
    }//GEN-LAST:event_mnuKRSSActionPerformed

    private void mnuMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMahasiswaActionPerformed
        // TODO add your handling code here:
        View.FrmMahasiswa objMhs = new View.FrmMahasiswa();
        objMhs.setLocationRelativeTo(this);
        objMhs.setVisible(true);
    }//GEN-LAST:event_mnuMahasiswaActionPerformed

    private void mnuMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMatakuliahActionPerformed
        View.FrmMatakuliah objMtk= new View.FrmMatakuliah();
        objMtk.setLocationRelativeTo(this);
        objMtk.setVisible(true);
    }//GEN-LAST:event_mnuMatakuliahActionPerformed

   
    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuKeluarActionPerformed

    private void mnuPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPeriodeActionPerformed
        View.FrmPeriode objPrd= new View.FrmPeriode();
        objPrd.setLocationRelativeTo(this);
        objPrd.setVisible(true);
    }//GEN-LAST:event_mnuPeriodeActionPerformed

    private void mnuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTransaksiActionPerformed
      
    }//GEN-LAST:event_mnuTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAkademik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem mnuCetakDataMahasiswa;
    private javax.swing.JMenuItem mnuCetakDataMatakuliah;
    private javax.swing.JMenuItem mnuCetakKRSS;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuKRSS;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenuItem mnuMahasiswa;
    private javax.swing.JMenuItem mnuMatakuliah;
    private javax.swing.JMenuItem mnuPeriode;
    private javax.swing.JMenu mnuTransaksi;
    // End of variables declaration//GEN-END:variables
}
